# nepali_events = {
#     "Nepali New Year": [1, "Baisakh"],
#     "Nepal Sambat New Year": [1, "Kartik"],
#     "Bisket Jatra": [1, "Baisakh"],
#     "Nepal Army Day": [19, "Chaitra"],
#     "Nepal Police Day": [1, "Ashar"],
#     "Rato Machindranath Jatra": ["Varies"],
#     "Buddha Jayanti": [10, "Baisakh"],
#     "Tamu Lhosar": [1, "Magh"],
#     "Saraswati Puja": [5, "Magh"],
#     "Martyrs' Day": [16, "Magh"],
#     "Lhosar (Sherpa New Year)": ["Varies"],
#     "National Democracy Day": [19, "Falgun"],
#     "Maha Shivaratri": [14, "Falgun"],
#     "International Women's Day": [8, "March"],
#     "Ghode Jatra": [1, "Chaitra"],
#     "Holi": [15, "Falgun"],
#     "Goddess Gadhimai Festival": ["Varies"],
#     "Bisket Jatra": ["Varies"],
#     "Budhha Jayanti": [10, "Baisakh"],
#     "Santoshi Mata Puja": [2, "Asar"],
#     "Guru Purnima": ["Full moon day in Ashadh"],
#     "Nag Panchami": [5, "Shrawan"],
#     "Gai Jatra": [1, "Bhadra"],
#     "Krishna Janmashtami": [2, "Bhadra"],
#     "Indra Jatra": [1, "Bhadra"],
#     "Rishi Panchami": [3, "Bhadra"],
#     "Teej": [3, "Bhadra"],
#     "Ganesh Chaturthi": [4, "Bhadra"],
#     "Indra Jatra": [1, "Bhadra"],
#     "Rishi Panchami": [3, "Bhadra"],
#     "Teej": [3, "Bhadra"],
#     "Ganesh Chaturthi": [4, "Bhadra"],
#     "Dashain": [10, "Ashwin"],
#     "Tihar": [2, "Kartik"],
#     "Maghe Sankranti": [1, "Magh"]
# }

nepali_events = {
    "Nepali New Year": "13 April",
    "Nepal Sambat New Year": "01 November",
    "Bisket Jatra": "13 April",
    "Nepal Army Day": "01 April",
    "Nepal Police Day": "14 June",
    "Rato Machindranath Jatra": "3 March",  # Random day in March
    "Buddha Jayanti": "10 April",
    "Tamu Lhosar": "14 January",
    "Saraswati Puja": "05 January",
    "Martyrs' Day": "30 January",
    "Lhosar (Sherpa New Year)": "5 February",  # Random day in February
    "National Democracy Day": "19 February",
    "Maha Shivaratri": "14 February",
    "International Women's Day": "08 March",
    "Ghode Jatra": "30 March",
    "Holi": "01 March",
    "Goddess Gadhimai Festival": "14 December",  # Random day in December
    "Bisket Jatra": " 15 April",  # Random day in April
    "Budhha Jayanti": "10 April",
    "Santoshi Mata Puja": "15 June",
    "Guru Purnima": "19 July",  # Random day in July
    "Nag Panchami": "19 July",
    "Gai Jatra": "17 August",
    "Krishna Janmashtami": "02 August",
    "Indra Jatra": "17 August",
    "Rishi Panchami": "19 August",
    "Teej": "19 August",
    "Ganesh Chaturthi": "20 August",
    "Indra Jatra": "17 August",
    "Rishi Panchami": "19 August",
    "Teej": "19 August",
    "Ganesh Chaturthi": "20 August",
    "Dashain": "25 September",
    "Tihar": "05 November",
    "Maghe Sankranti": "14 January"
}